// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MensajeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CortePDFAgentesParametro string `protobuf:"bytes,1,opt,name=cortePDFAgentesParametro,proto3" json:"cortePDFAgentesParametro,omitempty"`
}

func (x *MensajeRequest) Reset() {
	*x = MensajeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensajeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeRequest) ProtoMessage() {}

func (x *MensajeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeRequest.ProtoReflect.Descriptor instead.
func (*MensajeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *MensajeRequest) GetCortePDFAgentesParametro() string {
	if x != nil {
		return x.CortePDFAgentesParametro
	}
	return ""
}

type CreatePdf1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parametro *CortePDFAgentes `protobuf:"bytes,1,opt,name=parametro,proto3" json:"parametro,omitempty"`
}

func (x *CreatePdf1Request) Reset() {
	*x = CreatePdf1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePdf1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePdf1Request) ProtoMessage() {}

func (x *CreatePdf1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePdf1Request.ProtoReflect.Descriptor instead.
func (*CreatePdf1Request) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePdf1Request) GetParametro() *CortePDFAgentes {
	if x != nil {
		return x.Parametro
	}
	return nil
}

type CreatePdf1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreatePdf1Response) Reset() {
	*x = CreatePdf1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePdf1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePdf1Response) ProtoMessage() {}

func (x *CreatePdf1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePdf1Response.ProtoReflect.Descriptor instead.
func (*CreatePdf1Response) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePdf1Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgenteInfoM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreAgente          string                    `protobuf:"bytes,1,opt,name=NombreAgente,proto3" json:"NombreAgente,omitempty"`
	Id                    string                    `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Correo                string                    `protobuf:"bytes,3,opt,name=Correo,proto3" json:"Correo,omitempty"`
	Telefono              string                    `protobuf:"bytes,4,opt,name=Telefono,proto3" json:"Telefono,omitempty"`
	Direccion             string                    `protobuf:"bytes,5,opt,name=Direccion,proto3" json:"Direccion,omitempty"`
	ComisionAgenteResumen *ComisionAgenteResumenM   `protobuf:"bytes,6,opt,name=ComisionAgenteResumen,proto3" json:"ComisionAgenteResumen,omitempty"`
	ComisionAgenteDetalle []*ComisionAgenteDetalleM `protobuf:"bytes,7,rep,name=ComisionAgenteDetalle,proto3" json:"ComisionAgenteDetalle,omitempty"`
}

func (x *AgenteInfoM) Reset() {
	*x = AgenteInfoM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgenteInfoM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgenteInfoM) ProtoMessage() {}

func (x *AgenteInfoM) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgenteInfoM.ProtoReflect.Descriptor instead.
func (*AgenteInfoM) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AgenteInfoM) GetNombreAgente() string {
	if x != nil {
		return x.NombreAgente
	}
	return ""
}

func (x *AgenteInfoM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgenteInfoM) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *AgenteInfoM) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *AgenteInfoM) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *AgenteInfoM) GetComisionAgenteResumen() *ComisionAgenteResumenM {
	if x != nil {
		return x.ComisionAgenteResumen
	}
	return nil
}

func (x *AgenteInfoM) GetComisionAgenteDetalle() []*ComisionAgenteDetalleM {
	if x != nil {
		return x.ComisionAgenteDetalle
	}
	return nil
}

type ComisionAgenteResumenM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComisionServicios      float32 `protobuf:"fixed32,1,opt,name=ComisionServicios,proto3" json:"ComisionServicios,omitempty"`
	ComisionProductoInsumo float32 `protobuf:"fixed32,2,opt,name=ComisionProductoInsumo,proto3" json:"ComisionProductoInsumo,omitempty"`
	Subtotal               float32 `protobuf:"fixed32,3,opt,name=Subtotal,proto3" json:"Subtotal,omitempty"`
	Impuesto               float32 `protobuf:"fixed32,4,opt,name=Impuesto,proto3" json:"Impuesto,omitempty"`
	Total                  float32 `protobuf:"fixed32,5,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *ComisionAgenteResumenM) Reset() {
	*x = ComisionAgenteResumenM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComisionAgenteResumenM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComisionAgenteResumenM) ProtoMessage() {}

func (x *ComisionAgenteResumenM) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComisionAgenteResumenM.ProtoReflect.Descriptor instead.
func (*ComisionAgenteResumenM) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ComisionAgenteResumenM) GetComisionServicios() float32 {
	if x != nil {
		return x.ComisionServicios
	}
	return 0
}

func (x *ComisionAgenteResumenM) GetComisionProductoInsumo() float32 {
	if x != nil {
		return x.ComisionProductoInsumo
	}
	return 0
}

func (x *ComisionAgenteResumenM) GetSubtotal() float32 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *ComisionAgenteResumenM) GetImpuesto() float32 {
	if x != nil {
		return x.Impuesto
	}
	return 0
}

func (x *ComisionAgenteResumenM) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ComisionAgenteDetalleM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreServicio   string  `protobuf:"bytes,1,opt,name=NombreServicio,proto3" json:"NombreServicio,omitempty"`
	ComisionServicio float32 `protobuf:"fixed32,2,opt,name=ComisionServicio,proto3" json:"ComisionServicio,omitempty"`
	ComisionInsumo   float32 `protobuf:"fixed32,3,opt,name=ComisionInsumo,proto3" json:"ComisionInsumo,omitempty"`
	Total            float32 `protobuf:"fixed32,4,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *ComisionAgenteDetalleM) Reset() {
	*x = ComisionAgenteDetalleM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComisionAgenteDetalleM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComisionAgenteDetalleM) ProtoMessage() {}

func (x *ComisionAgenteDetalleM) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComisionAgenteDetalleM.ProtoReflect.Descriptor instead.
func (*ComisionAgenteDetalleM) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ComisionAgenteDetalleM) GetNombreServicio() string {
	if x != nil {
		return x.NombreServicio
	}
	return ""
}

func (x *ComisionAgenteDetalleM) GetComisionServicio() float32 {
	if x != nil {
		return x.ComisionServicio
	}
	return 0
}

func (x *ComisionAgenteDetalleM) GetComisionInsumo() float32 {
	if x != nil {
		return x.ComisionInsumo
	}
	return 0
}

func (x *ComisionAgenteDetalleM) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CortePDFAgentes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host                string         `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	DireccionPlataforma string         `protobuf:"bytes,2,opt,name=DireccionPlataforma,proto3" json:"DireccionPlataforma,omitempty"`
	CorreoPlataforma    string         `protobuf:"bytes,3,opt,name=CorreoPlataforma,proto3" json:"CorreoPlataforma,omitempty"`
	NumeroPlataforma    string         `protobuf:"bytes,4,opt,name=NumeroPlataforma,proto3" json:"NumeroPlataforma,omitempty"`
	CorteId             string         `protobuf:"bytes,5,opt,name=CorteId,proto3" json:"CorteId,omitempty"`
	FechaGenercion      string         `protobuf:"bytes,6,opt,name=FechaGenercion,proto3" json:"FechaGenercion,omitempty"`
	Periodo             string         `protobuf:"bytes,7,opt,name=Periodo,proto3" json:"Periodo,omitempty"`
	AgenteInfo          []*AgenteInfoM `protobuf:"bytes,8,rep,name=AgenteInfo,proto3" json:"AgenteInfo,omitempty"`
}

func (x *CortePDFAgentes) Reset() {
	*x = CortePDFAgentes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CortePDFAgentes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CortePDFAgentes) ProtoMessage() {}

func (x *CortePDFAgentes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CortePDFAgentes.ProtoReflect.Descriptor instead.
func (*CortePDFAgentes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *CortePDFAgentes) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CortePDFAgentes) GetDireccionPlataforma() string {
	if x != nil {
		return x.DireccionPlataforma
	}
	return ""
}

func (x *CortePDFAgentes) GetCorreoPlataforma() string {
	if x != nil {
		return x.CorreoPlataforma
	}
	return ""
}

func (x *CortePDFAgentes) GetNumeroPlataforma() string {
	if x != nil {
		return x.NumeroPlataforma
	}
	return ""
}

func (x *CortePDFAgentes) GetCorteId() string {
	if x != nil {
		return x.CorteId
	}
	return ""
}

func (x *CortePDFAgentes) GetFechaGenercion() string {
	if x != nil {
		return x.FechaGenercion
	}
	return ""
}

func (x *CortePDFAgentes) GetPeriodo() string {
	if x != nil {
		return x.Periodo
	}
	return ""
}

func (x *CortePDFAgentes) GetAgenteInfo() []*AgenteInfoM {
	if x != nil {
		return x.AgenteInfo
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0e, 0x4d,
	0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x18, 0x63, 0x6f, 0x72, 0x74, 0x65, 0x50, 0x44, 0x46, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x18, 0x63, 0x6f, 0x72, 0x74, 0x65, 0x50, 0x44, 0x46, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x22, 0x43, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x72, 0x74, 0x65, 0x50, 0x44, 0x46, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x65, 0x73, 0x52, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x22, 0x2e,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb1,
	0x02, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x12, 0x22,
	0x0a, 0x0c, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65,
	0x6c, 0x65, 0x66, 0x6f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x65,
	0x6c, 0x65, 0x66, 0x6f, 0x6e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x63,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x4d, 0x52, 0x15, 0x43, 0x6f,
	0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x6e, 0x12, 0x4d, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x4d, 0x52, 0x15, 0x43, 0x6f, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x4d, 0x12, 0x2c, 0x0a,
	0x11, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x12, 0x36, 0x0a, 0x16, 0x43,
	0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x49,
	0x6e, 0x73, 0x75, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x16, 0x43, 0x6f, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x49, 0x6e, 0x73,
	0x75, 0x6d, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x53, 0x75, 0x62, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x49, 0x6d, 0x70, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x49, 0x6d, 0x70, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x4d, 0x12, 0x26, 0x0a, 0x0e,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x69, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10,
	0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f,
	0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x75,
	0x6d, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x75, 0x6d, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xb9,
	0x02, 0x0a, 0x0f, 0x43, 0x6f, 0x72, 0x74, 0x65, 0x50, 0x44, 0x46, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x69, 0x72, 0x65, 0x63, 0x63,
	0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x44, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x6c,
	0x61, 0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x72, 0x72,
	0x65, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x61, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x12, 0x2a, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x50, 0x6c,
	0x61, 0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x72, 0x74, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x72, 0x74, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x46, 0x65,
	0x63, 0x68, 0x61, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x46, 0x65, 0x63, 0x68, 0x61, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x63, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x6f, 0x12, 0x2c, 0x0a, 0x0a,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x52, 0x0a,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x46, 0x0a, 0x0b, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x31, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x64, 0x66, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2b, 0x0a, 0x10, 0x70, 0x64, 0x66, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x50, 0x64, 0x66, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_goTypes = []interface{}{
	(*MensajeRequest)(nil),         // 0: MensajeRequest
	(*CreatePdf1Request)(nil),      // 1: CreatePdf1Request
	(*CreatePdf1Response)(nil),     // 2: CreatePdf1Response
	(*AgenteInfoM)(nil),            // 3: AgenteInfoM
	(*ComisionAgenteResumenM)(nil), // 4: ComisionAgenteResumenM
	(*ComisionAgenteDetalleM)(nil), // 5: ComisionAgenteDetalleM
	(*CortePDFAgentes)(nil),        // 6: CortePDFAgentes
}
var file_api_proto_depIdxs = []int32{
	6, // 0: CreatePdf1Request.parametro:type_name -> CortePDFAgentes
	4, // 1: AgenteInfoM.ComisionAgenteResumen:type_name -> ComisionAgenteResumenM
	5, // 2: AgenteInfoM.ComisionAgenteDetalle:type_name -> ComisionAgenteDetalleM
	3, // 3: CortePDFAgentes.AgenteInfo:type_name -> AgenteInfoM
	1, // 4: GeneratePdf.CreatePdf1:input_type -> CreatePdf1Request
	2, // 5: GeneratePdf.CreatePdf1:output_type -> CreatePdf1Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensajeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePdf1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePdf1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgenteInfoM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComisionAgenteResumenM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComisionAgenteDetalleM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CortePDFAgentes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeneratePdfClient is the client API for GeneratePdf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratePdfClient interface {
	CreatePdf1(ctx context.Context, in *CreatePdf1Request, opts ...grpc.CallOption) (*CreatePdf1Response, error)
}

type generatePdfClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratePdfClient(cc grpc.ClientConnInterface) GeneratePdfClient {
	return &generatePdfClient{cc}
}

func (c *generatePdfClient) CreatePdf1(ctx context.Context, in *CreatePdf1Request, opts ...grpc.CallOption) (*CreatePdf1Response, error) {
	out := new(CreatePdf1Response)
	err := c.cc.Invoke(ctx, "/GeneratePdf/CreatePdf1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratePdfServer is the server API for GeneratePdf service.
type GeneratePdfServer interface {
	CreatePdf1(context.Context, *CreatePdf1Request) (*CreatePdf1Response, error)
}

// UnimplementedGeneratePdfServer can be embedded to have forward compatible implementations.
type UnimplementedGeneratePdfServer struct {
}

func (*UnimplementedGeneratePdfServer) CreatePdf1(context.Context, *CreatePdf1Request) (*CreatePdf1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePdf1 not implemented")
}

func RegisterGeneratePdfServer(s *grpc.Server, srv GeneratePdfServer) {
	s.RegisterService(&_GeneratePdf_serviceDesc, srv)
}

func _GeneratePdf_CreatePdf1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePdf1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratePdfServer).CreatePdf1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeneratePdf/CreatePdf1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratePdfServer).CreatePdf1(ctx, req.(*CreatePdf1Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeneratePdf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GeneratePdf",
	HandlerType: (*GeneratePdfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePdf1",
			Handler:    _GeneratePdf_CreatePdf1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
